In [1]:
exec(open("./funcs/mmj_cal_functions.py").read())

In [2]:
import time

In [3]:
def cal_mmj_variant_of_Floyd_Warshall_python_dis_matrix(distance_matrix):
    n = len(distance_matrix)    
    p = distance_matrix.copy()
 
    for i in range(n):
        for j in range(n):
            if i != j:
                for k in range(n):
                    if i != k and j != k:
                        p[j,k] = min (p[j,k], max (p[j,i], p[i,k])) 
    return p

In [4]:
def cal_mmj_matrix_algo_1_python_dis_matrix(distance_matrix):
 
    N = len(distance_matrix)
   
    mmj_matrix = np.zeros((N,N))

    mmj_matrix[0,1] = distance_matrix[0,1]
    mmj_matrix[1,0] = distance_matrix[1,0]
 
    for kk in range(2,N):
        cal_n_mmj(distance_matrix, mmj_matrix, kk)
    return mmj_matrix

In [5]:
import numpy as np
import random

# create distance matrix of a directed graph

def create_distance_matrix(edges, num_nodes):
 
    dist_matrix = np.full((num_nodes, num_nodes), np.inf)
 
    np.fill_diagonal(dist_matrix, 0)
 
    for u, v, w in edges:
        dist_matrix[u, v] = w
    
    return dist_matrix

In [6]:

X_num_nodes = 200
X_plus_num_nodes = 201

edges = []

for u in range(X_plus_num_nodes):  
    for v in range(X_plus_num_nodes): 
        if u != v:
            w = int(random.uniform(1, 1000))
            edges.append((u, v, w))
 
X_plus_distance_matrix = create_distance_matrix(edges, X_plus_num_nodes)

print(X_plus_distance_matrix[:10, :10])  

[[  0. 851. 388. 132. 988. 541. 444. 811. 626. 464.]
 [241.   0. 903. 565. 424. 175. 158. 736.  22. 696.]
 [843. 898.   0.  57. 210. 888. 795. 456. 675. 963.]
 [536. 759. 729.   0. 488. 505. 100. 587. 370. 743.]
 [644. 647. 508.  22.   0. 115. 973. 530.  69. 672.]
 [323. 284. 474.  63. 217.   0. 444. 395. 899. 488.]
 [279. 446. 534. 726. 678. 200.   0. 577. 691. 467.]
 [ 37. 638. 792. 764. 251. 164. 821.   0. 630. 408.]
 [448. 416. 724. 431. 709. 454. 354. 484.   0. 223.]
 [943. 491.  18. 764. 225. 252.  82. 445. 744.   0.]]


In [7]:
X_distance_matrix = np.zeros((X_num_nodes,X_num_nodes))
for i in range(X_num_nodes):  
    for j in range(X_num_nodes): 
        X_distance_matrix[i,j] = X_plus_distance_matrix[i,j]
 


In [8]:
X_distance_matrix.shape

(200, 200)

In [9]:
X_plus_distance_matrix.shape

(201, 201)

In [10]:
print(X_distance_matrix[:5, :5])  

[[  0. 851. 388. 132. 988.]
 [241.   0. 903. 565. 424.]
 [843. 898.   0.  57. 210.]
 [536. 759. 729.   0. 488.]
 [644. 647. 508.  22.   0.]]


In [11]:
print(X_plus_distance_matrix[:5, :5])  

[[  0. 851. 388. 132. 988.]
 [241.   0. 903. 565. 424.]
 [843. 898.   0.  57. 210.]
 [536. 759. 729.   0. 488.]
 [644. 647. 508.  22.   0.]]


In [12]:
# Test cold-start calculation of the APPD matrix by variant of the Floyd-Warshall algorithm.


start = time.time()
X_plus_mmj_matrix_Floyd_Warshall_python = cal_mmj_variant_of_Floyd_Warshall_python_dis_matrix(X_plus_distance_matrix)
end = time.time()
time_used = end - start
time_used = np.round(time_used, 3)
print(f"Cold start calculation of the APPD matrix by Floyd-Warshall algorithm, time_used: {time_used}s.")


Cold start calculation of the APPD matrix by Floyd-Warshall algorithm, time_used: 6.778s.


In [13]:
X_mmj_matrix = cal_mmj_matrix_algo_1_python_dis_matrix(X_distance_matrix)

In [14]:
X_mmj_matrix.shape

(200, 200)

In [15]:
def cal_mmj_matrix_algo_1_warm_start_new(X_plus_distance_matrix, X_mmj_matrix):
    
 
    N = len(X_mmj_matrix)
    
    N_plus_one = N + 1
   
    X_plus_mmj_matrix = np.zeros((N_plus_one, N_plus_one))
    
    for i in range(N):
        for j in range(N):
            X_plus_mmj_matrix[i,j] = X_mmj_matrix[i,j]
            
    cal_n_mmj(X_plus_distance_matrix, X_plus_mmj_matrix, N)
 
    return X_plus_mmj_matrix

In [16]:
# Test warm-start calculation of the APPD matrix by Algorithm 1.
 
start = time.time()
X_plus_mmj_matrix_algo_1_warm = cal_mmj_matrix_algo_1_warm_start_new(X_plus_distance_matrix, X_mmj_matrix)
end = time.time()
time_used = end - start
time_used = np.round(time_used, 3)

print(f"Warm-start calculation of the APPD matrix by Algorithm 1, time_used: {time_used}s.")

Warm-start calculation of the APPD matrix by Algorithm 1, time_used: 0.947s.


In [17]:

print(np.allclose(X_plus_mmj_matrix_Floyd_Warshall_python, X_plus_mmj_matrix_algo_1_warm))
print(np.sum(np.abs(X_plus_mmj_matrix_Floyd_Warshall_python - X_plus_mmj_matrix_algo_1_warm)))


True
0.0


In [18]:
# Therefore, we can conclude warm-start of Algorithm 1 is faster than cold-start of other algorithms.
# This is especially useful when the graph is a directed dense graph, where we cannot use
# Algorithm 4 (MMJ distance by Calculation and Copy).