In [1]:
exec(open("./funcs/mmj_cal_functions.py").read())
exec(open("./funcs/Prim_Minimum_Spanning_Tree.py").read())
 

In [2]:
# wides_path_exam_graph, widest path problem example graph, 
# see the upper right graph on https://en.wikipedia.org/wiki/Widest_path_problem

pairwise_bandwidth_matrix = pickle.load(  open( "./data/wides_path_exam_graph.p", "rb" )) 
 

In [3]:
pairwise_bandwidth_matrix

array([[inf, 15., 53.,  0.,  0.,  0.,  0.],
       [15., inf, 40.,  0.,  0., 46.,  0.],
       [53., 40., inf, 17., 31.,  0.,  0.],
       [ 0.,  0., 17., inf, 29.,  0., 40.],
       [ 0.,  0., 31., 29., inf,  3.,  8.],
       [ 0., 46.,  0.,  0.,  3., inf, 11.],
       [ 0.,  0.,  0., 40.,  8., 11., inf]])

In [4]:
graph_nodes_names = {'Dunwich':0, 'Blaxhall':1, 'Harwich':2, 'Clacton':3, 'Tiptree':4, 'Feering':5, 'Maldon':6}



In [5]:
Widest_path_matrix_algo_4 = cal_Widest_path_problem_matrix_by_algo_4(pairwise_bandwidth_matrix)
Widest_path_matrix_algo_4



array([[ 0., 40., 53., 29., 31., 40., 29.],
       [40.,  0., 40., 29., 31., 46., 29.],
       [53., 40.,  0., 29., 31., 40., 29.],
       [29., 29., 29.,  0., 29., 29., 40.],
       [31., 31., 31., 29.,  0., 31., 29.],
       [40., 46., 40., 29., 31.,  0., 29.],
       [29., 29., 29., 40., 29., 29.,  0.]])

In [6]:
i = graph_nodes_names["Maldon"]
j = graph_nodes_names["Feering"]

Widest_path_matrix_algo_4[i,j]


29.0

In [7]:
N = len(pairwise_bandwidth_matrix)
for i in range(N):
    Widest_path_matrix_algo_4[i,i] = np.inf

In [8]:
Widest_path_matrix_algo_4

array([[inf, 40., 53., 29., 31., 40., 29.],
       [40., inf, 40., 29., 31., 46., 29.],
       [53., 40., inf, 29., 31., 40., 29.],
       [29., 29., 29., inf, 29., 29., 40.],
       [31., 31., 31., 29., inf, 31., 29.],
       [40., 46., 40., 29., 31., inf, 29.],
       [29., 29., 29., 40., 29., 29., inf]])

In [9]:
# See Section 7 (SOLVING THE WIDEST PATH PROBLEM) of the paper:
# https://arxiv.org/abs/2301.05994

def wpp_n_to_r(distance_matrix, widest_path_matrix, n, r):
    max_jump_list = []
    for ttt in range(n):
        m_jump = np.min((distance_matrix[n,ttt],widest_path_matrix[ttt,r]))
        max_jump_list.append(m_jump)
    return np.max(max_jump_list)

def wpp_r_to_n(distance_matrix, widest_path_matrix, n, r):
    max_jump_list = []
    for ttt in range(n):
        m_jump = np.min((widest_path_matrix[r,ttt], distance_matrix[ttt, n]))
        max_jump_list.append(m_jump)
    return np.max(max_jump_list)

     
def cal_n_wpp(distance_matrix, widest_path_matrix, n):
    for i in range(n):
        widest_path_matrix[n,i] = wpp_n_to_r(distance_matrix, widest_path_matrix, n, i)
        widest_path_matrix[i,n] = wpp_r_to_n(distance_matrix, widest_path_matrix, n, i)
        
    for i in range(n):        
        for j in range(n):
            if i < j:
                widest_path_matrix[i,j] =  update_wpp_ij(distance_matrix, widest_path_matrix, n, i, j)
                widest_path_matrix[j,i] =  update_wpp_ij(distance_matrix, widest_path_matrix, n, j, i)
                
def update_wpp_ij(distance_matrix, widest_path_matrix, n, i,j):
    m1 = widest_path_matrix[i,j]
    m2 = np.min((widest_path_matrix[i,n],widest_path_matrix[n,j]))
    return np.max((m1,m2))

def cal_widest_path_matrix_algo_1_python(distance_matrix):
 
    N = len(distance_matrix)
   
    widest_path_matrix = np.ones((N,N))*np.inf

    widest_path_matrix[0,1] = distance_matrix[0,1]
    widest_path_matrix[1,0] = distance_matrix[1,0]
 
    for kk in range(2, N):
        cal_n_wpp(distance_matrix, widest_path_matrix, kk)
    return widest_path_matrix

In [10]:
Widest_path_matrix_algo_1 = cal_widest_path_matrix_algo_1_python(pairwise_bandwidth_matrix)
Widest_path_matrix_algo_1

array([[inf, 40., 53., 29., 31., 40., 29.],
       [40., inf, 40., 29., 31., 46., 29.],
       [53., 40., inf, 29., 31., 40., 29.],
       [29., 29., 29., inf, 29., 29., 40.],
       [31., 31., 31., 29., inf, 31., 29.],
       [40., 46., 40., 29., 31., inf, 29.],
       [29., 29., 29., 40., 29., 29., inf]])

In [11]:
i = graph_nodes_names["Maldon"]
j = graph_nodes_names["Feering"]

Widest_path_matrix_algo_1[i,j]

29.0

In [12]:
print(np.allclose(Widest_path_matrix_algo_1, Widest_path_matrix_algo_4))


True
